// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckNanobotInstalled():Promise<string>;

export function ClearChannelMessages():Promise<void>;

export function ClearGatewayLogs():Promise<void>;

export function ClearMessages():Promise<void>;

export function CreateBot(arg1:string,arg2:string):Promise<Record<string, any>>;

export function DeleteBot(arg1:string):Promise<void>;

export function GetActiveBot():Promise<Record<string, any>>;

export function GetBotConfig(arg1:string):Promise<string>;

export function GetChannelMessages():Promise<Array<main.ChannelMessage>>;

export function GetChannels():Promise<Record<string, any>>;

export function GetConfig():Promise<string>;

export function GetGatewayLogs():Promise<string>;

export function GetGatewayStatus():Promise<main.GatewayStatus>;

export function GetMessages():Promise<Array<main.ChatMessage>>;

export function GetNanobotInfo():Promise<Record<string, any>>;

export function GetProviders():Promise<Record<string, any>>;

export function GetSessions():Promise<Array<main.SessionInfo>>;

export function GetSetupState():Promise<Record<string, any>>;

export function GetSystemInfo():Promise<Record<string, string>>;

export function HideWindow():Promise<void>;

export function IsHidden():Promise<boolean>;

export function ListBots():Promise<Array<Record<string, any>>>;

export function NavigateTo(arg1:string):Promise<void>;

export function OpenInFinder(arg1:string):Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function Quit():Promise<void>;

export function RestartGateway():Promise<void>;

export function SaveConfig(arg1:string):Promise<void>;

export function SendMessage(arg1:string):Promise<void>;

export function SetChannelField(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetNanobotPath(arg1:string):Promise<void>;

export function SetProviderAPIKey(arg1:string,arg2:string):Promise<void>;

export function SetupSaveConfig(arg1:string,arg2:string):Promise<void>;

export function ShowAndNavigate(arg1:string):Promise<void>;

export function ShowWindow():Promise<void>;

export function StartGateway():Promise<void>;

export function StopGateway():Promise<void>;

export function SwitchBot(arg1:string):Promise<void>;

export function ToggleFullscreen():Promise<void>;

export function UpdateBot(arg1:string,arg2:string,arg3:string):Promise<void>;
