// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearChannelMessages() {
  return window['go']['main']['App']['ClearChannelMessages']();
}

export function ClearGatewayLogs() {
  return window['go']['main']['App']['ClearGatewayLogs']();
}

export function ClearMessages() {
  return window['go']['main']['App']['ClearMessages']();
}

export function GetChannelMessages() {
  return window['go']['main']['App']['GetChannelMessages']();
}

export function GetChannels() {
  return window['go']['main']['App']['GetChannels']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetGatewayLogs() {
  return window['go']['main']['App']['GetGatewayLogs']();
}

export function GetGatewayStatus() {
  return window['go']['main']['App']['GetGatewayStatus']();
}

export function GetMessages() {
  return window['go']['main']['App']['GetMessages']();
}

export function GetProviders() {
  return window['go']['main']['App']['GetProviders']();
}

export function GetSessions() {
  return window['go']['main']['App']['GetSessions']();
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function IsHidden() {
  return window['go']['main']['App']['IsHidden']();
}

export function NavigateTo(arg1) {
  return window['go']['main']['App']['NavigateTo'](arg1);
}

export function OpenInFinder(arg1) {
  return window['go']['main']['App']['OpenInFinder'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function RestartGateway() {
  return window['go']['main']['App']['RestartGateway']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SendMessage(arg1) {
  return window['go']['main']['App']['SendMessage'](arg1);
}

export function SetChannelField(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetChannelField'](arg1, arg2, arg3);
}

export function SetProviderAPIKey(arg1, arg2) {
  return window['go']['main']['App']['SetProviderAPIKey'](arg1, arg2);
}

export function ShowAndNavigate(arg1) {
  return window['go']['main']['App']['ShowAndNavigate'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function StartGateway() {
  return window['go']['main']['App']['StartGateway']();
}

export function StopGateway() {
  return window['go']['main']['App']['StopGateway']();
}

export function ToggleFullscreen() {
  return window['go']['main']['App']['ToggleFullscreen']();
}
